[package]
name = "rost"
version = "0.1.0"
authors = ["Alex <alex@42layers.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0"
thiserror = "1.0"
either = "1.6"
